name: fixed
version: 1.0.3
homepage: https://github.com/bsutton/fixed
description: Fixed scale decimal numbers with mathematical operations, formatting and parsing.
repository: https://github.com/bsutton/fixed
environment:
  sdk: '>=2.14.0 <3.0.0'
dependencies:
  decimal: ^2.0.0
  intl: ^0.17.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
